### ISSUE TITLE
New-Plan card: increase spacing between text

### ISSUE THREAD

**Issue by jonathandavidlewis** [awaywego/awaywego#135]

**Comment by jonathandavidlewis** [comment]
![awaywego-01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cc3a5c8dc03a00123e8e7b/125516c66e82c728ace21e0d46e9839b3a9586ae80a4ef12e611b2843b492d762a10e17132d0ba2de9412f560a0a1aa842510a44fdf1dc2af4b06e798e4e17ff933c0120996048e6edc00db513bb27814e80b6b58a4dc1ea3a21e2828b5d73.jpg)

**Comment by AtreidesEnd** [comment]
no longer relevant, closing as wontfix
